{% set name = "cpcm-x" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}-pkg
  version: {{ version }}

source:
  url: https://github.com/grimme-lab/CPCM-X/releases/download/v{{ version }}/cpx-{{ version }}.tar.xz
  sha256: 255dfa9b70c41580163fa3636125a0103c3b553c52fc8558d3a63f4654cc41c1
  patches:
    - gh61.patch

build:
  number: 2

outputs:
  - name: {{ name }}
    script: build_pkg.sh   # [unix]
    script: build_pkg.bat  # [win]
    build:
      string: {{ module_abi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }}
    requirements:
      build:
        - {{ stdlib("c") }}
        - {{ compiler("c") }}
        - {{ compiler("fortran") }}
        - meson
        - ninja
        - pkg-config
      host:
        - libblas
        - liblapack
        - libgomp  # [not osx]
        - mctc-lib-devel * {{ module_abi }}_*
        - numsa-devel * {{ module_abi }}_*
        - toml-f-devel * {{ module_abi }}_*

    test:
      requires:
        - pkg-config
      commands:
        - cpx --help  # [build_platform == target_platform]
        - test -f $PREFIX/lib/libcpx$SHLIB_EXT  # [unix]
        - if not exist "%LIBRARY_PREFIX%\bin\libcpx-1.dll" exit /b 1  # [win]
        - pkg-config cpx --exact-version {{ version }}

  - name: {{ name }}-devel
    build:
      string: {{ module_abi }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
      run_exports:
        - {{ pin_subpackage(name, max_pin='x.x') }} {{ module_abi }}_*

    requirements:
      run:
        - {{ pin_subpackage(name, max_pin='x.x') }} {{ module_abi }}_*

    test:
      requires:
        - pkg-config
      commands:
        - cpx --help  # [build_platform == target_platform]
        - test -f $PREFIX/lib/libcpx$SHLIB_EXT  # [unix]
        - if not exist "%LIBRARY_PREFIX%\bin\libcpx-1.dll" exit /b 1  # [win]
        - pkg-config cpx --exact-version {{ version }}

about:
  home: https://github.com/grimme-lab/cpcm-x
  license: LGPL-3.0-or-later
  license_file:
    - LICENSE
  summary: Extended conductor-like polarizable continuum solvation model

extra:
  recipe-maintainers:
    - awvwgk
  feedstock-name: {{ name }}
